### PR TITLE
Updating .gitignore

### PR DESCRIPTION
**Pull request by mnemoniko**

### CODE REVIEW

**Comment by mnemoniko** [comment]
Sorry - having trouble getting github to pull request into my local branch

**Comment by kshedstrom** [comment]
Do you need help with something? Did you fork my repo? If so, you should be able to push to it.

**Comment by mnemoniko** [comment]
I think I just need to get better at using git.  I've used ROMS for awhile, but have been pretty bad at keeping the code updated.  

I recently forked your repo, and tried to add a branch from my local machine that I originally downloaded last October or so.  I *almost* got it to work, but had trouble with the Apps folder.  Do I need to separately fork a copy of Apps as well, since it's a submodule?

My objective is to have a fork of your repo to sync the latest ROMS updates, both your updates to the ice-relevant code, and the general ROMS updates.  I'd have a local branch of that fork that includes my updates (from some of my PhD work), and some of Mike Dinniman's code (I originally got ROMS from him).  Then I could selectively push updates to my local files, and if I have code that might be of interest to other users, submit pull requests to your repo.  Does this sound like a reasonable approach?

**Comment by kshedstrom** [comment]
Yes, you need to clone the Apps repo as well. I'm still learning about
submodules, not sure it was a good idea to make Apps a submodule after it's
been a simple directory for so long. Now I've got different Apps repos for
different ROMS branches, not pretty.

Yes, that's how github is supposed to work for collaborative code
development. Too bad there's no working path back to Hernan's code - I gave
up years ago.

Kate

**Pull request closed without merging**
